#pragma once

#include <Hooks/Memory.h>

class EXCO_ErrorMessage
{
public:
	enum Error : s32
	{
		UNKNOWN = 0,
		NET_GENERAL_ERROR = 1,
		NET_GENERAL_ERROR_LAN = 2,
		NET_CONNECTION_BROKEN = 3,
		NET_CONNECTION_REFUSED = 4,
		NET_CONNECTION_UNREACHABLE = 5,
		NET_CONNECTION_BANNED = 6,
		NET_SERVER_FULL = 7,
		NET_SERVER_AUTH_FAILED = 8,
		NET_SERVER_CLOSED = 9,
		NET_SERVER_WRONG_VERSION = 10,
		NET_SERVER_WRONG_PASSWORD = 11,
		NET_SERVER_UDP_TIMEOUT = 12,
		NET_LOCAL_ERROR = 13,
		NET_UNKNOWN_COMMAND = 14,
		LOAD_ERROR_ON_MISSION_INIT = 15,
		LOAD_ERROR_ON_PLAYER_INIT = 16,
		LOBBY_SERVER_CONNECTION_LOST = 17,
		MASSGATE_DISCONNECTED = 18,
		MASSGATE_NOTIFICATION = 19,
		DISCONNECTED_IDLE = 20,
		DISCONNECTED_FF = 21,
		DISCONNECTED_KICK = 22,
		DISCONNECTED_KICKBAN = 23,
		WARNING_SPAM = 24,
		WARNING_REQUEST_SPAM = 25,
		WARNING_TEAMBALANCE = 26,
		WARNING_TEAMBALANCED = 27,
		HOST_SHUTDOWN = 28,
		LOBBYIST_HOST_SHUTDOWN = 29,
		NUM_ERRORS = 30,
	};

	static inline DeclareGlobalRef(EXCO_ErrorMessage *, ourInstance, SelectOffset(0x00E1F528, 0x0));

	void AddError(const wchar_t *anErrorString, Error anError, const char *aDestinationGUI);
};