#pragma once

#define EX_MAX_NUM_PLAYERS 16
#define EX_MAX_NUM_CLIENTS 16
#define EX_MAX_NUM_UNITS 512
#define EX_MAX_SHOOTER_TARGETS 8

class EXCO_Constants
{
public:
	enum ScreenMessageType : s32
	{
		SCREENMSG_SYSTEM = 0x0,
		SCREENMSG_GAME = 0x1,
		SCREENMSG_CHATALL = 0x2,
		SCREENMSG_CHATTEAM = 0x3,
		SCREENMSG_TAUNT = 0x4,
		SCREENMSG_VOTE = 0x5,
		SCREENMSG_COMMANDPOINT = 0x6,
		SCREENMSG_REQUEST = 0x7,
		SCREENMSG_DEBUG = 0x8,
	};

	enum PlayerAction : s32
	{
		AGENT_SELECTED = 0x0,
		AGENT_SELECTED_MULTIPLE = 0x1,
		REINFORCEMENTS_SCREEN_PRESSED = 0x2,
		UNIT_BOUGHT = 0x3,
		SPAWNER_DEPLOY = 0x4,
		UNITS_DEPLOYED = 0x5,
		MEGAMAP_PRESSED = 0x6,
		MEGAMAP_CLOSED = 0x7,
		SKIP_CUTSCENE = 0x8,
		TACTICAL_AID_SCREEN_PRESSED = 0x9,
		TACTICAL_AID_CHOOSEN = 0xA,
		OBJECTIVE_BROWSER_ACTIVATED = 0xB,
		OBJECTIVE_BROWSER_DEACTIVATED = 0xC,
		END_OF_CUTSCENE = 0xD,
		CLICKED_MINIMAP = 0xE,
		CLICKED_RESTARTLESSION = 0xF,
		CLICKED_SKIPLESSION = 0x10,
		CLICKED_NEXTLESSION = 0x11,
		CLICKED_FINISHLESSION = 0x12,
		ENTER_DROPZONE_MODE = 0x13,
		DROPZONE_PLACED = 0x14,
		CLICKED_SPECIAL_ABILITY = 0x15,
		USED_SPECIAL_ABILITY = 0x16,
		NO_ACTION = 0x17,
		NUM_ACTIONS = 0x18,
	};
};